# Generated by Django 5.1.4 on 2025-01-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_img',
            field=models.ImageField(upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='my_projects',
            name='project_img',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
