# Generated by Django 5.1.4 on 2025-01-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_about_about_img_alter_my_projects_project_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
